### ISSUE TITLE
[19.02.02] EMR 본진 파트의 예진항목 명칭 수정

### ISSUE THREAD

**Issue by JunhoeKim** [Freemd-it/Freemed-EMR#32]
EMR 본진 파트의 환자별 예진정보 탭을 확인해보면 Heart Rate 항목이 있습니다. 해당 항목이 Heart Rate 항목이 아니라 SpO2 항목의 수치인 것 같아 명칭 수정 부탁드립니다.

**Comment by JunhoeKim** [comment]
@urbanscenery 
확인한 결과 DB상에서 기존의 heart rate가 SPO2고 pulse rate는 heart rate로 가야한다고 합니다.

**Comment by freemedicalservice** [comment]
@urbanscenery  4월 10일까지 부탁드립니다~

**Comment by urbanscenery** [comment]
#55 로 이슈 완료합니다. 닫는건 @JunhoeKim 가 해주세요.
