### ISSUE TITLE
[19.02.16] EMR 본진 파트의 예진정보 탭에 세부내용 추가

### ISSUE THREAD

**Issue by JunhoeKim** [Freemd-it/Freemed-EMR#33]
EMR 본진 파트의 예진정보 탭을 확인해보면 성별 항목이 따로 없어서 의사 선생님께서 진료시 조금 불편하시다고 합니다. 혹시 가능하다면 추가 부탁드립니다.

**Comment by freemedicalservice** [comment]
@devPil 4월 6일까지 부탁드립니다!

**Comment by devPil** [comment]
[Pull Request](https://github.com/Freemd-it/Freemed-EMR/pull/52)
