### ISSUE TITLE
[19.02.16] EMR 본진 파트의 환자정보 탭에 세부내용 추가

### ISSUE THREAD

**Issue by JunhoeKim** [Freemd-it/Freemed-EMR#34]
EMR 본진 파트의 환자정보 탭을 확인해보면 생년월일만 있고 나이는 따로 기재되어 있지 않습니다. 생년월일 뿐만아니라 나이 항목도 추가되면 진료시 조금 더 수월할 것 같다고 하십니다. 혹시 가능하다면 추가 부탁드리겠습니다.

**Comment by freemedicalservice** [comment]
@whitewolf23 4월 6일까지 부탁드립니다~
