### ISSUE TITLE
바이탈사인 그래프 확인부탁드립니다.

### ISSUE THREAD

**Issue by freemedicalservice** [Freemd-it/Freemed-EMR#46]
바이탈 사인 그래프 값이 환자분이 바뀌어도 바뀌지 않습니다. 즉, 과거진료 기록과 예진기록에는 혈당, 혈압 수치등이 제대로 업로드되지만 새로 생긴 바이탈사인 그래프는 고정값으로 설정되어 바뀌지 않습니다. 수정 부탁드립니다.

**Comment by JunhoeKim** [comment]
@freemedicalservice 특정 수혜자분만 그런것인가요? 아니면 전체적으로 어느 정보에서 고정되어 있다는 뜻인가요??? 원래도 복약지도까지 마쳐야 바이탈사인 차트에 새로 적용되는 것으로 알고 있습니다.
