### ISSUE TITLE
월별 환자목록현황 자료 부탁드립니다.

### ISSUE THREAD

**Issue by freemedicalservice** [Freemd-it/Freemed-EMR#59]
의무기록팀에서 효율적인 OCS 관리를 위해 월별로 수혜자 명단을 확인하고자 합니다.
매달 마지막째주 진료소가 끝나면 그 달까지 기록된 환자목록현황 자료를 받고 싶습니다.
기한은 마지막째주 진료소가 끝난 토요일로부터 1주일 이내로 파일을 전달해주시면 감사하겠습니다.
항상 감사합니다.

**Comment by whitewolf23** [comment]
넵 내일 전달해 드리겠습니다
