### ISSUE TITLE
현재까지 등록된 수혜자 명단 부탁드립니다.

### ISSUE THREAD

**Issue by freemedicalservice** [Freemd-it/Freemed-EMR#61]
의무기록팀에서 수혜자분들을 대상으로 설문을 진행하고자 합니다.
이를 위해서 수혜자분들의 기본정보가 필요할 것 같아 현재까지 등록된 수혜자 명단을 받고 싶습니다.
다음주 진료소에서 설문을 시행할 예정이라 5월 30일까지 전달해주시면 감사하겠습니다.
감사합니다.

**Comment by urbanscenery** [comment]
진행하겠습니다.

**Comment by urbanscenery** [comment]
05/18 진료소 수혜자 명단까지 엑셀파일로 의무기록팀장 메일로 전달드렸습니다.
