### ISSUE TITLE
[약무] 특정 약품이 처방 입력 되지 않음 

### ISSUE THREAD

**Issue by freemedicalservice** [Freemd-it/Freemed-EMR#64]
새로운 약품(알리코시메티딘정200mg)이 들어와서 EMR에 약품 추가를 하였습니다. 
의사선생님 아이디에서 약전에 해당 약품이 검색은 되지만 눌렀을 때 처방에 추가가 되지 않는 오류가 발생하였습니다. 
약사선생님 아이디에서는 검색도 되고 처방에 추가도 된다고 합니다.
이전에는 이런 오류가 발생한 적이 없었습니다.

**Comment by JunhoeKim** [comment]
의사, 약사 둘 다 본진에서 처방에 추가하는 과정에서 생기는 오류라는 뜻인가요? 해결한 이슈랑은 별개인 것 같은데 이제야 발견된 것 같습니다.

**Comment by freemedicalservice** [comment]
의사선생님 아이디로 본진에서 새로 들어온 약을 처방에 추가하는 과정에서 생기는 오류 입니다.

이전에 새로운 약이 들어왔을 때에는 아무 문제가 없었습니다.

**Comment by JunhoeKim** [comment]
약사 아이디로 본진에서 처방하는 것에서는 문제가 생기지 않는다면 정말 이상하네요... 혹시 staging에서 테스트 해볼 수 있는 환경을 제공해주실 수 있나요 잔디로 부탁드립니다~
