### ISSUE TITLE
[의기] 2019년 2분기 자료 요청드립니다.

### ISSUE THREAD

**Issue by freemedicalservice** [Freemd-it/Freemed-EMR#67]
1. 6월  29일까지 EMR에 누적되어 있는 환자목록현황 요청드립니다. 등록번호, 첫 방문일자, 성함, 성별, 생년월일이 포함되어 있는 누적 데이터 부탁드립니다.

2. 2019년 2분기, 4월부터 6월까지의 환자데이터 요청드립니다. EMR에 기록된 환자가 호소한 증상, 의사선생님 진단내용, 처방내역 등 수혜자 의료데이터 자료 부탁드립니다. 가능하다면 혈압 수치도 포함시켜주시면 감사하겠습니다.

감사합니다.

**Comment by whitewolf23** [comment]
확인했습니다.

**Comment by whitewolf23** [comment]
6월 29일에 환자 한분이 생년월일이 다르게 등록된것이 있는데, 혹시 확인해 주실 수 있으면 감사하겠습니다. 말씀해주시면 바로 변경하겠습니다.

**Comment by JunhoeKim** [comment]
@whitewolf23 이거 확인 완료됐나요?

**Comment by whitewolf23** [comment]
넵 닫아도 됩니다
