### ISSUE TITLE
[의기] 7월 진료소 데이터 요청드립니다

### ISSUE THREAD

**Issue by freemedicalservice** [Freemd-it/Freemed-EMR#69]
의무기록팀에서 분기별로 생산하던 지표를 월별로 생산하고자 합니다. 다음과 같은 7월 데이터 부탁드립니다.

1. 7월 27일까지 EMR에 누적되어 있는 환자목록현황 요청드립니다. 등록번호, 첫 방문일자, 성함, 성별, 생년월일이 포함되어 있는 누적 데이터 부탁드립니다.

2. 2019년 7월의 환자데이터 요청드립니다. EMR에 기록된 환자가 호소한 증상, 의사선생님 진단내용, 처방내역 등 수혜자 의료데이터 자료 부탁드립니다. 가능하다면 혈압 수치도 포함시켜주시면 감사하겠습니다.

감사합니다.

**Comment by whitewolf23** [comment]
오늘 자정에 처리하겠습니다.

**Comment by JunhoeKim** [comment]
@whitewolf23 이거 마무리 된 이슈죠?
